event_types:
  - no_event
  - home_run
  - out
  - hit

event_scores:
  home_run: 4.0
  out: 2.0
  hit: 1.0
  no_event: 0.0

confidence_thresholds:
  min: 0.7
  high: 0.9

temporal_weights:
  start: 1.0
  middle: 1.1
  end: 1.2

multipliers:
  home_run:
    confidence: 1.2
    late_game: 1.3
    sequence: 1.1
  out:
    confidence: 1.1
    late_game: 1.2
    sequence: 1.2
  hit:
    confidence: 1.1
    late_game: 1.2
    sequence: 1.2

analysis_window: 100
min_events_for_stats: 10